### ISSUE TITLE
[Bug]: Remove padding from UsageBar

### ISSUE THREAD

**Issue by clarkmcc** [ChrisUser/react-usage-bar#14]
### What happened?

Is it possible to remove the padding from the UsageBar? My personal opinion is that child components shouldn't enforce on the parent how the child is allowed to lay out on the page.
![image](https://github.com/ChrisUser/react-usage-bar/assets/6639685/beb47338-8ed2-47ff-83fb-ce335b90b7be)

![image](https://github.com/ChrisUser/react-usage-bar/assets/6639685/b6b6e43a-7834-4319-a25c-10dba78e295e)

### Version

1.1.22

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisUser** [comment]
Hi @clarkmcc, sorry for the late reply.
I think you made a really good point here, don't know what i was thinking when I put that extra padding there.

I'll surely integrate this fix in the next release, which will also include the other issue you brought up (#15).

**Comment by clarkmcc** [comment]
Thank you very much!
